---
name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ec-cli
        run: |-
          mkdir -p "${HOME}/.local/bin"
          curl -sL https://github.com/enterprise-contract/ec-cli/releases/download/snapshot/ec_linux_amd64 -o "${HOME}/.local/bin/ec"
          chmod +x "${HOME}/.local/bin/ec"
          ec version

      - name: Validate data
        run: ./hack/verify-data.sh

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ec-cli
        run: |-
          mkdir -p "${HOME}/.local/bin"
          curl -sL https://github.com/enterprise-contract/ec-cli/releases/download/snapshot/ec_linux_amd64 -o "${HOME}/.local/bin/ec"
          chmod +x "${HOME}/.local/bin/ec"
          ec version

      - name: Install cosign
        run: |-
          curl -sL https://github.com/sigstore/cosign/releases/download/v2.4.3/cosign-linux-amd64 -o "${HOME}/.local/bin/cosign"
          chmod +x "${HOME}/.local/bin/cosign"
          cosign version

      - name: Validate data
        run: ./hack/smoke-test.sh
